ls:
  .auto.tfvars: kebab-case
  .json: kebab-case
  .tf: kebab-case
  .tfvars: kebab-case
  .yaml: kebab-case
  .yml: kebab-case

ignore:
  - '**/.commitlintrc.json'
  - '**/.eslintrc.json'
  - '**/.git'
  - '**/.lintstagedrc-*.js'
  - '**/.lintstagedrc-*.json'
  - '**/.lintstagedrc.js'
  - '**/.lintstagedrc.json'
  - '**/.ls-lint.yml'
  - '**/.pnpm'
  - '**/.prettierrc.json'
  - '**/.sops.yaml'
  - '**/.syncpackrc.json'
  - '**/.terraform'
  - '**/.terraform-docs.yaml'
  - '**/.tfsec'
  - '**/node_modules'
