#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh"

set -e
set -u
set -o pipefail

diff_before="$(git diff --no-ext-diff --no-textconv --ignore-submodules | base64)"

pnpm install --ignore-scripts
git add package.json

pnpm run init
pnpm run typecheck
pnpm run lint-staged

diff_after="$(git diff --no-ext-diff --no-textconv --ignore-submodules | base64)"

if [[ "${diff_before}" != "${diff_after}" ]]; then
  echo "files were modified by the pre-commit hook"
  exit 1
fi
