name: release
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
jobs:
  reelase:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: install dependencies
        run: |
          npm install -g pnpm
          pnpm install
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
